### ISSUE TITLE
Science without Borders snippet

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/programmes-plant#768]
As International Development

I would like a 'Science without borders' checkbox in the programmes plant so I can check programmes that are in this scheme. I would also like a version of the courses summary snippet that will allow me to diplay all the courses that have been checked. Programme page links in the summary snippet would go to the central course catalogue. 

So we can effectively promote this scheme and the courses included in it. 

(Summary of existing story - https://github.com/unikent/programmes-plant/issues/667)

**Comment by aw285-unikent** [comment]
@eg270-unikent is this still blocked?

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent no it's not still blocked. However, it is quite a large chunk of work to create the pantheon snippet, probably at least 2-3 days of development. 
Therefore, it's significantly larger than a BAU day. We may have some time at the end of the next sprint (around 20th january - dependent on progress with our blogs sprint), but otherwise it will have to be bundled into a sprint to address other of-course/programmes plant issues.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent we've added this as part of #689 but no courses appear to be marked as "Science without borders" in the current year's programmes plant

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent I have emailed Katie and Nathan in ID to ask for a list of courses that need to be checked (copied you in). Thanks, Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent I can't remember if we got a response from Katie and Nathan regarding this one.

**Comment by aw285-unikent** [comment]
@eg270-unikent I was sent a spreadsheet of programmes and have asked @frithassell to check the checkbox for the relevant programmes and confirm when this is done.
