### ISSUE TITLE
Missing (non-mandatory) fields in xcri cap

### ISSUE THREAD

**Issue by jna-unikent** [unikent/programmes-plant#832]
The following fields aren't being included in the xcri-cap feed at all:
 - credit
 - qualification->educationLevel
 - presentation->subject

Do we care about these at all? They are not mandatory but may be useful to have on prospects.

**Comment by eg270-unikent** [comment]
@aw285-unikent do you want us to add these fields?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent. I don't think we can add credit because although we have the credit values and could easily add the schemes (University of Kent; ECTS), we don't have the 'level' data in the programmes plant (a mandatory field) so this would be an additional data overhead which we probably don't have time to sort out at the moment. 
Educationlevel eg 'undergraduate' or 'postgraduate' would be good to add. 
Is 'subject' already in the feed at 'course' level? If so, I think it inherits the 'course' level subject for the presentation one, if there isn't a subject specified at presentation level?

**Comment by eg270-unikent** [comment]
https://github.com/unikent/programmes-plant/pull/864
